# salesforce settings for databasedotcom gem (Sandbox) -- CloudSpokes localhost remove access
client_id: 3MVG9_7ddP9KqTzdCEqrJi8EiCVqIcfbXqjuRfyBMa3UNUHw2dNZrjbcaif5WJ_h18qY.5nMc0oYsEqthLU97
client_secret: 6135129799238543535
host: test.salesforce.com
debugging: true