class Country < ActiveHash::Base
  self.data = [
    {:id => 10, :name => "Antarctica"},
    {:id => 11, :name => "Antigua and Barbuda"},
    {:id => 12, :name => "Argentina"},
    {:id => 13, :name => "Armenia"},
    {:id => 14, :name => "Aruba"},
    {:id => 15, :name => "Ascension Island"},
    {:id => 16, :name => "Australia"},
    {:id => 17, :name => "Austria"},
    {:id => 18, :name => "Azerbaijan"},
    {:id => 19, :name => "Bahamas"},
    {:id => 20, :name => "Bahrain"},
    {:id => 21, :name => "Bangladesh"},
    {:id => 22, :name => "Barbados"},
    {:id => 23, :name => "Belarus"},
    {:id => 24, :name => "Belgium"},
    {:id => 25, :name => "Belize"},
    {:id => 26, :name => "Benin"},
    {:id => 27, :name => "Bermuda"},
    {:id => 28, :name => "Bhutan"},
    {:id => 29, :name => "Bolivia"},
    {:id => 30, :name => "Bophuthatswana"},
    {:id => 31, :name => "Bosnia-Herzegovina"},
    {:id => 32, :name => "Botswana"},
    {:id => 33, :name => "Bouvet Island"},
    {:id => 34, :name => "Brazil"},
    {:id => 35, :name => "British Indian Ocean"},
    {:id => 36, :name => "British Virgin Islands"},
    {:id => 37, :name => "Brunei Darussalam"},
    {:id => 38, :name => "Bulgaria"},
    {:id => 39, :name => "Burkina Faso"},
    {:id => 40, :name => "Burundi"},
    {:id => 41, :name => "Cambodia"},
    {:id => 42, :name => "Cameroon"},
    {:id => 242, :name => "Canada"},
    {:id => 44, :name => "Cape Verde Island"},
    {:id => 45, :name => "Cayman Islands"},
    {:id => 46, :name => "Central Africa"},
    {:id => 47, :name => "Chad"},
    {:id => 48, :name => "Channel Islands"},
    {:id => 49, :name => "Chile"},
    {:id => 50, :name => "China, Peoples Republic"},
    {:id => 51, :name => "Christmas Island"},
    {:id => 52, :name => "Cocos (Keeling) Islands"},
    {:id => 53, :name => "Colombia"},
    {:id => 54, :name => "Comoros Islands"},
    {:id => 55, :name => "Congo"},
    {:id => 56, :name => "Cook Islands"},
    {:id => 57, :name => "Costa Rica"},
    {:id => 58, :name => "Croatia"},
    {:id => 59, :name => "Cuba"},
    {:id => 60, :name => "Cyprus"},
    {:id => 61, :name => "Czech Republic"},
    {:id => 62, :name => "Denmark"},
    {:id => 63, :name => "Djibouti"},
    {:id => 64, :name => "Dominica"},
    {:id => 65, :name => "Dominican Republic"},
    {:id => 66, :name => "Easter Island"},
    {:id => 67, :name => "Ecuador"},
    {:id => 68, :name => "Egypt"},
    {:id => 69, :name => "El Salvador"},
    {:id => 70, :name => "England"},
    {:id => 71, :name => "Equatorial Guinea"},
    {:id => 72, :name => "Estonia"},
    {:id => 73, :name => "Ethiopia"},
    {:id => 75, :name => "Faeroe Islands"},
    {:id => 74, :name => "Falkland Islands"},
    {:id => 76, :name => "Fiji"},
    {:id => 77, :name => "Finland"},
    {:id => 78, :name => "France"},
    {:id => 79, :name => "French Guyana"},
    {:id => 80, :name => "French Polynesia"},
    {:id => 81, :name => "Gabon"},
    {:id => 82, :name => "Gambia"},
    {:id => 83, :name => "Georgia Republic"},
    {:id => 84, :name => "Germany"},
    {:id => 85, :name => "Gibraltar"},
    {:id => 86, :name => "Greece"},
    {:id => 87, :name => "Greenland"},
    {:id => 88, :name => "Grenada"},
    {:id => 89, :name => "Guadeloupe (French)"},
    {:id => 90, :name => "Guatemala"},
    {:id => 91, :name => "Guernsey Island"},
    {:id => 93, :name => "Guinea"},
    {:id => 92, :name => "Guinea Bissau"},
    {:id => 94, :name => "Guyana"},
    {:id => 95, :name => "Haiti"},
    {:id => 96, :name => "Heard and McDonald Isls"},
    {:id => 97, :name => "Honduras"},
    {:id => 98, :name => "Hong Kong"},
    {:id => 99, :name => "Hungary"},
    {:id => 100, :name => "Iceland"},
    {:id => 101, :name => "India"},
    {:id => 102, :name => "Iran"},
    {:id => 103, :name => "Iraq"},
    {:id => 104, :name => "Ireland"},
    {:id => 105, :name => "Isle of Man"},
    {:id => 106, :name => "Israel"},
    {:id => 107, :name => "Italy"},
    {:id => 108, :name => "Ivory Coast"},
    {:id => 109, :name => "Jamaica"},
    {:id => 110, :name => "Japan"},
    {:id => 111, :name => "Jersey Island"},
    {:id => 112, :name => "Jordan"},
    {:id => 113, :name => "Kazakhstan"},
    {:id => 114, :name => "Kenya"},
    {:id => 115, :name => "Kiribati"},
    {:id => 116, :name => "Kuwait"},
    {:id => 117, :name => "Laos"},
    {:id => 118, :name => "Latvia"},
    {:id => 119, :name => "Lebanon"},
    {:id => 120, :name => "Lesotho"},
    {:id => 121, :name => "Liberia"},
    {:id => 122, :name => "Libya"},
    {:id => 123, :name => "Liechtenstein"},
    {:id => 124, :name => "Lithuania"},
    {:id => 125, :name => "Luxembourg"},
    {:id => 126, :name => "Macao"},
    {:id => 127, :name => "Macedonia"},
    {:id => 128, :name => "Madagascar"},
    {:id => 129, :name => "Malawi"},
    {:id => 130, :name => "Malaysia"},
    {:id => 131, :name => "Maldives"},
    {:id => 132, :name => "Mali"},
    {:id => 133, :name => "Malta"},
    {:id => 134, :name => "Martinique (French)"},
    {:id => 135, :name => "Mauritania"},
    {:id => 136, :name => "Mauritius"},
    {:id => 137, :name => "Mayotte"},
    {:id => 243, :name => "Mexico"},
    {:id => 139, :name => "Micronesia"},
    {:id => 140, :name => "Moldavia"},
    {:id => 141, :name => "Monaco"},
    {:id => 142, :name => "Mongolia"},
    {:id => 143, :name => "Montenegro"},
    {:id => 144, :name => "Montserrat"},
    {:id => 145, :name => "Morocco"},
    {:id => 146, :name => "Mozambique"},
    {:id => 147, :name => "Myanmar"},
    {:id => 148, :name => "Namibia"},
    {:id => 149, :name => "Nauru"},
    {:id => 150, :name => "Nepal"},
    {:id => 152, :name => "Netherlands"},
    {:id => 151, :name => "Netherlands Antilles"},
    {:id => 153, :name => "New Caledonia (French)"},
    {:id => 154, :name => "New Zealand"},
    {:id => 155, :name => "Nicaragua"},
    {:id => 156, :name => "Niger"},
    {:id => 157, :name => "Niue"},
    {:id => 158, :name => "Norfolk Island"},
    {:id => 159, :name => "North Korea"},
    {:id => 160, :name => "Northern Ireland"},
    {:id => 161, :name => "Norway"},
    {:id => 162, :name => "Oman"},
    {:id => 163, :name => "Pakistan"},
    {:id => 164, :name => "Panama"},
    {:id => 165, :name => "Papua New Guinea"},
    {:id => 166, :name => "Paraguay"},
    {:id => 167, :name => "Peru"},
    {:id => 168, :name => "Philippines"},
    {:id => 169, :name => "Pitcairn Island"},
    {:id => 170, :name => "Poland"},
    {:id => 171, :name => "Polynesia (French)"},
    {:id => 172, :name => "Portugal"},
    {:id => 173, :name => "Qatar"},
    {:id => 174, :name => "Reunion Island"},
    {:id => 175, :name => "Romania"},
    {:id => 176, :name => "Russia"},
    {:id => 177, :name => "Rwanda"},
    {:id => 178, :name => "S.Georgia Sandwich Isls"},
    {:id => 180, :name => "San Marino"},
    {:id => 179, :name => "Sao Tome, Principe"},
    {:id => 181, :name => "Saudi Arabia"},
    {:id => 182, :name => "Scotland"},
    {:id => 183, :name => "Senegal"},
    {:id => 184, :name => "Serbia"},
    {:id => 185, :name => "Seychelles"},
    {:id => 186, :name => "Shetland"},
    {:id => 187, :name => "Sierra Leone"},
    {:id => 188, :name => "Singapore"},
    {:id => 189, :name => "Slovak Republic"},
    {:id => 190, :name => "Slovenia"},
    {:id => 191, :name => "Solomon Islands"},
    {:id => 192, :name => "Somalia"},
    {:id => 193, :name => "South Africa"},
    {:id => 194, :name => "South Korea"},
    {:id => 195, :name => "Spain"},
    {:id => 196, :name => "Sri Lanka"},
    {:id => 197, :name => "St. Helena"},
    {:id => 201, :name => "St. Kitts Nevis Anguilla"},
    {:id => 198, :name => "St. Lucia"},
    {:id => 200, :name => "St. Martins"},
    {:id => 199, :name => "St. Pierre Miquelon"},
    {:id => 202, :name => "St. Vincent Grenadines"},
    {:id => 203, :name => "Sudan"},
    {:id => 204, :name => "Suriname"},
    {:id => 205, :name => "Svalbard Jan Mayen"},
    {:id => 206, :name => "Swaziland"},
    {:id => 207, :name => "Sweden"},
    {:id => 208, :name => "Switzerland"},
    {:id => 209, :name => "Syria"},
    {:id => 212, :name => "Tahiti"},
    {:id => 211, :name => "Taiwan"},
    {:id => 210, :name => "Tajikistan"},
    {:id => 213, :name => "Tanzania"},
    {:id => 214, :name => "Thailand"},
    {:id => 215, :name => "Togo"},
    {:id => 216, :name => "Tokelau"},
    {:id => 217, :name => "Tonga"},
    {:id => 218, :name => "Trinidad and Tobago"},
    {:id => 219, :name => "Tunisia"},
    {:id => 220, :name => "Turkmenistan"},
    {:id => 221, :name => "Turks and Caicos Isls"},
    {:id => 222, :name => "Tuvalu"},
    {:id => 223, :name => "Uganda"},
    {:id => 224, :name => "Ukraine"},
    {:id => 225, :name => "United Arab Emirates"},
    {:id => 1, :name => "United States"},
    {:id => 226, :name => "Uruguay"},
    {:id => 227, :name => "Uzbekistan"},
    {:id => 228, :name => "Vanuatu"},
    {:id => 229, :name => "Vatican City State"},
    {:id => 230, :name => "Venezuela"},
    {:id => 231, :name => "Vietnam"},
    {:id => 232, :name => "Virgin Islands (Brit)"},
    {:id => 233, :name => "Wales"},
    {:id => 234, :name => "Wallis Futuna Islands"},
    {:id => 235, :name => "Western Sahara"},
    {:id => 236, :name => "Western Samoa"},
    {:id => 237, :name => "Yemen"},
    {:id => 238, :name => "Yugoslavia"},
    {:id => 239, :name => "Zaire"},
    {:id => 240, :name => "Zambia"},
    {:id => 241, :name => "Zimbabwe"}
  ]
end